name: 修改微信步数

on:
  workflow_dispatch:
  schedule:
    - cron: '35 2 * * *'
    - cron: '30 2 * * *'

    


jobs: 
  ChangBuShu: 
    runs-on: ubuntu-latest
    if: true
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        
    - name: 安装环境
      run: pip install -r ./requirements.txt
      
    - name: 修改步数
      run: python3 changebushu_Action.py
      env:
        USER_PHONE: "19811869008"  # 直接写入手机号
        USER_PWD: "wxy15865726726@"  # 直接写入密码
        STEP: "27000"  # 确定的步数值。如果要随机步数，可以删除此行。
        STEP_MIN: "25000"  # 随机步数的最小值
        STEP_MAX: "30000"  # 随机步数的最大值
      
